name             'sixpack_ab'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures sixpack'
long_description 'Installs/Configures sixpack'
version          '0.1.0'

depends 'git', '~> 4.0.2'
depends 'python', '~> 1.4.6'
depends 'redisio', '~> 1.7.1'